EXPERIMENT_RUN: 002

MODEL:
    PROTOTYPE_DISTANCE_FUNCTION: "cosine"
    PROTOTYPE_ACTIVATION_FUNCTION: "linear"
    # BACKBONE: "pretrained_backbones/40w-64-deep_6.pth"
    BACKBONE: "saved_models/backbones/family_new_aug_1/family_new_aug_1_best.pth"
    # BACKBONE: "saved_models/backbones/genus_aug/genus_aug_best.pth"
    # BACKBONE: "saved_models/backbones/species_Metriocnemus/species_Metriocnemus_best.pth"

DATASET:
    NAME: "genetics"
    # NUM_CLASSES: 8
    NUM_CLASSES: 40
    TRAIN_BATCH_SIZE: 80
    TEST_BATCH_SIZE: 100

    GENETIC:
        SIZE: 720
        TAXONOMY_NAME: "family"
        # TAXONOMY_NAME: "species"
        ORDER_NAME: "Diptera"
        TRANSFORM: "onehot"
        PROTOTYPE_SHAPE: (1600, 64, 1, 1) # 40 * DATASET_NUM_CLASSES
        # PROTOTYPE_SHAPE: (600, 64, 1, 1) # 40 * DATASET_NUM_CLASSES
        FIX_PROTOTYPES: True
        TRAIN_PATH: "datasets/genetics/small_diptera_family-train.tsv"
        TRAIN_PUSH_DIR: "datasets/genetics/small_diptera_family-train.tsv"
        VALIDATION_PATH: "datasets/genetics/small_diptera_family-validation.tsv"
        # TRAIN_PATH: "datasets/genetics/large_diptera_family-train-temp_augmented.tsv"
        # TRAIN_PUSH_DIR: "datasets/genetics/large_diptera_family-train-temp_chopped.tsv"
        # VALIDATION_PATH: "datasets/genetics/large_diptera_family-validation.tsv"

OUTPUT:
    NO_SAVE: False
    MODEL_DIR: "saved_models/genetics/diptera_test_new_1"
    IMG_DIR: "saved_models/genetics/diptera_test_new_1"
    PROTOTYPE_IMG_FILENAME_PREFIX: "genetic-string"
OPTIM:
    PUSH_START: 0
    NUM_WARM_EPOCHS: 5
    PUSH_EPOCHS: [0, 5, 10, 20, 30, 40, 50, 60, 70, 80]
    # COEFS:
    # SEP: -.04
    # CLST: .5
    # CRS_ENT: 1.5
# EXPERIMENT_RUN: 003

# MODEL:
#     PROTOTYPE_DISTANCE_FUNCTION: "cosine"
#     PROTOTYPE_ACTIVATION_FUNCTION: "linear"
#     BACKBONE: "pretrained_backbones/40w-64-deep_6.pth"

# DATASET:
#     NAME: "genetics"
#     NUM_CLASSES: 40
#     TRAIN_BATCH_SIZE: 80
#     TEST_BATCH_SIZE: 100

#     GENETIC:
#         SIZE: 720
#         TAXONOMY_NAME: "family"
#         ORDER_NAME: "Diptera"
#         TRANSFORM: "onehot"
#         PROTOTYPE_SHAPE: (1600, 64, 1, 1) # 40 * DATASET_NUM_CLASSES
#         FIX_PROTOTYPES: True
#         TRAIN_PATH: "datasets/genetics/small_diptera_family-train.tsv"
#         TRAIN_PUSH_DIR: "datasets/genetics/small_diptera_family-train.tsv"
#         VALIDATION_PATH: "datasets/genetics/small_diptera_family-validation.tsv"

# OUTPUT:
#     NO_SAVE: False
#     MODEL_DIR: "saved_models/genetics/prototype_saving_test"
#     IMG_DIR: "saved_models/genetics/prototype_saving_test_images/real_run"
#     PROTOTYPE_IMG_FILENAME_PREFIX: "genetic-string"
# OPTIM:
#     PUSH_START: 10
#     PUSH_EPOCHS: [0, 10, 20, 30, 40, 50, 60, 70, 80]
