EXPERIMENT_RUN: 001

MODEL:
    # PROTOTYPE_SHAPE: (400, 128, 1, 1)
    PROTOTYPE_DISTANCE_FUNCTION: 'cosine'
    PROTOTYPE_ACTIVATION_FUNCTION: 'linear'


DATASET:
    NAME: bioscan
    NUM_CLASSES: 40
    IMAGE:
        SIZE: 256
        TRAIN_DIR: "datasets/bioscan/small_diptera_train"
        TEST_DIR: "datasets/bioscan/small_diptera_test"
        TRAIN_PUSH_DIR: "datasets/bioscan/small_diptera_train"
        TRAIN_BATCH_SIZE: 80
        TRANSFORM_MEAN: (0.485, 0.456, 0.406)
        TRANSFORM_STD: (0.229, 0.224, 0.225)

OUTPUT:
    MODEL_DIR: "./saved_models"
    IMG_DIR: "./saved_models/bioscan/img"
    WEIGHT_MATRIX_FILENAME: 'outputL_weights'
    PROTOTYPE_IMG_FILENAME_PREFIX: 'prototype-img'
    PROTOTYPE_SELF_ACT_FILENAME_PREFIX: 'prototype-self-act'
    PROTO_BOUND_BOXES_FILENAME_PREFIX: 'bb'
